"""
utils.py - Production-grade SQL validation using sqlglot AST parsing.
Enforces: SELECT-only, no raw SELECT *, user isolation via property_users, table whitelist, LIMIT injection.
"""

import os
import re
import logging
import sqlglot
from sqlglot import exp
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("chatbot_api")

# Read allowed tables from environment variable
_allowed_tables_str = os.getenv(
    "ALLOWED_TABLES",
    "properties,property_users,inspection_reports,inspection_report_findings,"
    "inspection_report_structures,clearances,invoices,payment_histories,"
    "property_repair_jobs,property_fumigation_jobs"
)
ALLOWED_TABLES = {t.strip().lower() for t in _allowed_tables_str.split(",") if t.strip()}

BANNED_OPERATIONS = {"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE", "REPLACE", "GRANT", "REVOKE", "EXEC"}


def validate_sql_query(query: str, expected_user_id: int) -> str:
    """
    Validates and hardens an LLM-generated SQL query before execution.

    Checks performed:
    1. Must be a SELECT statement (no DML/DDL).
    2. Raw SELECT * is blocked (table.* is allowed for JOINs).
    3. Only whitelisted tables from ALLOWED_TABLES env var are permitted.
    4. A WHERE clause filtering by property_users.user_id = expected_user_id must exist,
       OR users.id = expected_user_id for direct user lookups.
    5. A LIMIT clause is injected if missing (default 50).

    Args:
        query: The raw SQL string generated by the LLM.
        expected_user_id: The authenticated user's ID that must appear in WHERE.

    Returns:
        The validated and potentially modified SQL string.

    Raises:
        ValueError: If the query fails any validation check.
    """
    query = query.strip().rstrip(";")

    # --- Step 0: Quick regex guard against banned keywords ---
    query_upper = query.upper()
    for word in BANNED_OPERATIONS:
        if re.search(rf"\b{word}\b", query_upper):
            raise ValueError(f"Banned SQL operation detected: {word}")

    # --- Step 1: Parse with sqlglot ---
    try:
        parsed = sqlglot.parse_one(query, dialect="mysql")
    except sqlglot.errors.ParseError as e:
        raise ValueError(f"SQL parse error: {e}")

    # --- Step 2: Must be a SELECT ---
    if not isinstance(parsed, exp.Select):
        raise ValueError("Only SELECT queries are allowed.")

    # --- Step 3: Block raw SELECT * ---
    # We allow `table.*` since LangChain uses it for JOINs, but block generic `*`
    for expression in parsed.expressions:
        if type(expression) is exp.Star:
            raise ValueError(
                "Raw SELECT * is not allowed. Please specify explicit column names or table.* aliases."
            )

    # --- Step 4: Table whitelist ---
    tables_used = set()
    for table in parsed.find_all(exp.Table):
        table_name = table.name.lower()
        tables_used.add(table_name)
        if table_name not in ALLOWED_TABLES:
            raise ValueError(f"Querying unauthorized table: '{table.name}'. Only these tables are allowed: {', '.join(sorted(ALLOWED_TABLES))}")

    # --- Step 5: Enforce user isolation via property_users ---
    # The LLM must JOIN property_users and filter by property_users.user_id = expected_user_id
    # We search for any EQ node where one side is a column named 'user_id' and the other is the expected value
    user_id_found = False

    for eq in parsed.find_all(exp.EQ):
        for node in [eq.left, eq.right]:
            if isinstance(node, exp.Column) and node.name.lower() == "user_id":
                # Check if this column belongs to property_users (or has no table prefix)
                table_prefix = node.table.lower() if node.table else ""
                if table_prefix in ("property_users", "pu", ""):
                    other_node = eq.right if node is eq.left else eq.left
                    if isinstance(other_node, exp.Literal) and str(other_node.this) == str(expected_user_id):
                        user_id_found = True
                        break
        if user_id_found:
            break

    if not user_id_found:
        raise ValueError(
            f"Query must filter by property_users.user_id = {expected_user_id}. "
            "All queries must JOIN property_users to enforce user data isolation."
        )

    # --- Step 6: Verify property_users is actually in the query ---
    if "property_users" not in tables_used:
        raise ValueError(
            "Query must include the property_users table to enforce user data isolation. "
            "JOIN property_users ON property_users.property_id = <table>.property_id"
        )

    # --- Step 7: Inject LIMIT if missing ---
    if parsed.args.get("limit") is None:
        parsed = parsed.limit(50)

    validated_sql = parsed.sql(dialect="mysql")
    logger.info(f"SQL validation passed: {validated_sql}")
    return validated_sql
